<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/12/27
 * Time: 16:21
 */

namespace app\admin\controller;


use app\common\controller\Backend;

class Slide extends Backend
{
    public $model = null;

    public function _initialize()
    {
         parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('slide_show');
    }
}