<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/1/8
 * Time: 17:13
 */

namespace app\admin\controller;


use app\common\controller\Backend;

class Software extends Backend
{
    public $model = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('software');
    }
}