<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/12/24
 * Time: 15:32
 */

namespace app\admin\controller\article;


use app\common\controller\Backend;
use app\common\logic\ArticleCategory;

class Article extends Backend
{
    protected $model;
    protected $categoryLogic;
    protected $multiFields="id,name,is_top";

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('Article');
        $this->categoryLogic = new ArticleCategory();
        $this->view->assign("parentList", $this->categoryLogic->categorydata);
    }
    /**
     * 查看
     */
    public function index()
    {
        if ($this->request->isAjax()) {
            //如果发送的来源是Selectpage，则转发到Selectpage
            if ($this->request->request('keyField')) {
                return $this->selectpage();
            }
            list($where, $sort, $order, $offset, $limit) = $this->buildparams();
            $total = $this->model
                ->with('ArticleCategory')
                ->where($where)
                ->order($sort)
                ->count();

            $list = $this->model
                ->with('ArticleCategory')
                ->where($where)
                ->order($sort)
                ->limit($offset, $limit)
                ->select();

            $result = array("total" => $total, "rows" => $list);

            return json($result);
        }
        return $this->view->fetch();
    }
}