<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/1/9
 * Time: 15:25
 */

namespace app\index\controller;


use app\common\controller\Frontend;

class Article extends Frontend
{
    protected $noNeedLogin = '*';
    protected $noNeedRight = '*';
    protected $layout = 'index_default';
    protected $model;
    protected $categoryMod;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('article');
        $this->categoryMod = model('article_category');
        $categoryList = $this->categoryMod->where('status','normal')->order('weigh desc')->select();
        $this->assign('categoryList',$categoryList);
    }

    public function detail()
    {
        $id = $this->request->param('id');
        if (empty($id)){
            $this->error('id不能为空');
        }
        $res = $this->model->with('admin')->where('article.id', $id)->find();
        $this->assign('res', $res);
        return $this->view->fetch();
    }
}